name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        rust: [stable] # TODO MSRV

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --all-targets --all-features
      env:
        RUSTFLAGS: -D warnings

    - name: Test
      run: cargo test --all

  docs:
    name: Docs

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build documentation
      run: cargo doc --all-features --no-deps --document-private-items
      env:
        RUSTDOCFLAGS: -D warnings

  lints:
    name: Lints

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
      env:
        RUSTFLAGS: -D warnings
