name: Nightly

on:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false

      matrix:
        rust: [stable, beta, nightly]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --all-targets --all-features
      env:
        RUSTFLAGS: -D warnings

    - name: Test
      run: cargo test --all
