name: Nightly

on:
  schedule:
  - cron: 0 0 * * 0 # weekly

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build
      run: cargo build --all-targets
      env:
        RUSTFLAGS: -D warnings
    - name: Test
      run: cargo test --no-fail-fast --all-features
